# Generated by Django 5.2.11 on 2026-02-23 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("extraction_method", models.CharField(blank=True, max_length=30)),
                ("page_count", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("total_tags_found", models.PositiveIntegerField(default=0)),
                ("tags_valid_active", models.PositiveIntegerField(default=0)),
                ("tags_valid_void", models.PositiveIntegerField(default=0)),
                ("tags_not_found", models.PositiveIntegerField(default=0)),
                ("tags_shorthand", models.PositiveIntegerField(default=0)),
                (
                    "overall_result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("issues", "Has Issues"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "document_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_sessions",
                        to="documents.documentrevision",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Session",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tag_number", models.CharField(db_index=True, max_length=50)),
                ("raw_text", models.CharField(blank=True, max_length=200)),
                ("is_shorthand", models.BooleanField(default=False)),
                ("original_shorthand", models.CharField(blank=True, max_length=200)),
                (
                    "page_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("confidence", models.FloatField(default=1.0)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("valid_active", "Valid — Active"),
                            ("valid_void", "Valid — Void (flag)"),
                            ("not_found", "Not Found"),
                            ("shorthand_detected", "Shorthand Detected"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ctdb_description", models.TextField(blank=True)),
                ("ctdb_discipline", models.CharField(blank=True, max_length=100)),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_results",
                        to="assets.tag",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="verification.verificationsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Result",
                "ordering": ["session", "tag_number"],
                "indexes": [
                    models.Index(
                        fields=["session", "verification_status"],
                        name="verificatio_session_314fa8_idx",
                    ),
                    models.Index(
                        fields=["tag_number"], name="verificatio_tag_num_c4a501_idx"
                    ),
                ],
            },
        ),
    ]
