# Generated by Django 5.2.11 on 2026-02-23 10:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CriticalityLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("safety_sil3", "Safety Critical — SIL 3"),
                            ("safety_sil2", "Safety Critical — SIL 2"),
                            ("safety_sil1", "Safety Critical — SIL 1"),
                            ("production", "Production Critical"),
                            ("asset", "Asset Critical"),
                            ("non_critical", "Non-Critical"),
                        ],
                        default="non_critical",
                        max_length=20,
                    ),
                ),
                ("colour", models.CharField(blank=True, max_length=7)),
                (
                    "requires_rcm",
                    models.BooleanField(
                        default=False, help_text="Reliability-Centred Maintenance"
                    ),
                ),
                ("requires_sil_study", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Criticality Level",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("abbreviation", models.CharField(blank=True, max_length=5)),
                (
                    "colour",
                    models.CharField(
                        blank=True, help_text="Hex colour, e.g. #FF5733", max_length=7
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Discipline",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("create", "Create New Tag"),
                            ("update", "Update Tag Details"),
                            ("void", "Void Tag"),
                            ("reactivate", "Reactivate Tag"),
                            ("obsolete", "Mark Obsolete"),
                            ("delete", "Delete Tag"),
                        ],
                        max_length=20,
                    ),
                ),
                ("proposed_tag_number", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("justification", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("implemented", "Implemented"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("implemented_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "implemented_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="implemented_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("escalated", "Escalated"),
                            ("info_required", "Information Required"),
                        ],
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="assets.changerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Approval",
                "ordering": ["change_request", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="ChangeRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField()),
                ("notes", models.TextField(blank=True)),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="assets.changerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Request Item",
                "ordering": ["field_name"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV Upload"),
                            ("excel", "Excel Upload"),
                            ("api", "API Import"),
                            ("seed", "System Seed"),
                        ],
                        default="csv",
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial (some rows failed)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_log", models.TextField(blank=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Batch",
                "verbose_name_plural": "Import Batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("operator", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant / Facility",
                "verbose_name_plural": "Plants / Facilities",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="assets.plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area",
                "ordering": ["plant", "code"],
                "unique_together": {("plant", "code")},
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("system_number", models.CharField(blank=True, max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System",
                "ordering": ["unit", "code"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tag_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique tag number, e.g. 10-P-101A",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Tag number must be uppercase alphanumeric with hyphens, 2-31 chars.",
                                regex="^[A-Z0-9][A-Z0-9\\-]{1,30}$",
                            )
                        ],
                    ),
                ),
                ("tag_description", models.TextField(blank=True)),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="Alternative name / nickname",
                        max_length=100,
                    ),
                ),
                ("abbreviation", models.CharField(blank=True, max_length=20)),
                (
                    "service_description",
                    models.TextField(
                        blank=True, help_text="Process service description"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Void", "Void"),
                            ("Provisional", "Provisional"),
                            ("Obsolete", "Obsolete"),
                            ("Reserved", "Reserved"),
                        ],
                        db_index=True,
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "status_reason",
                    models.TextField(blank=True, help_text="Reason for current status"),
                ),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("line_number", models.CharField(blank=True, max_length=50)),
                ("drawing_number", models.CharField(blank=True, max_length=100)),
                (
                    "p_and_id_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="P&ID Number"
                    ),
                ),
                ("spec_number", models.CharField(blank=True, max_length=50)),
                ("datasheet_number", models.CharField(blank=True, max_length=50)),
                ("purchase_order_number", models.CharField(blank=True, max_length=50)),
                ("work_order_number", models.CharField(blank=True, max_length=50)),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("model_number", models.CharField(blank=True, max_length=100)),
                (
                    "serial_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("material", models.CharField(blank=True, max_length=100)),
                (
                    "size_rating",
                    models.CharField(
                        blank=True, help_text='e.g. 4" Class 300', max_length=50
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "design_pressure_barg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Design Pressure (barg)",
                    ),
                ),
                (
                    "design_temperature_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Design Temperature (°C)",
                    ),
                ),
                (
                    "is_safety_critical",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("is_pressure_vessel", models.BooleanField(default=False)),
                ("is_lifting_equipment", models.BooleanField(default=False)),
                (
                    "is_atex_rated",
                    models.BooleanField(default=False, verbose_name="ATEX Rated"),
                ),
                (
                    "sil_level",
                    models.CharField(
                        blank=True,
                        help_text="SIL 1 / SIL 2 / SIL 3 / SIL 4",
                        max_length=10,
                    ),
                ),
                ("designed_at", models.DateField(blank=True, null=True)),
                ("fabricated_at", models.DateField(blank=True, null=True)),
                ("installed_at", models.DateField(blank=True, null=True)),
                ("commissioned_at", models.DateField(blank=True, null=True)),
                ("last_inspected_at", models.DateField(blank=True, null=True)),
                ("next_inspection_due", models.DateField(blank=True, null=True)),
                ("decommissioned_at", models.DateField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "maintenance_strategy",
                    models.CharField(
                        blank=True,
                        help_text="PM / PdM / RCM / Run-to-Failure",
                        max_length=50,
                    ),
                ),
                (
                    "maintenance_interval_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("spare_parts_available", models.BooleanField(default=False)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="assets.area",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criticality_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="assets.criticalitylevel",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="assets.discipline",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="assets.plant",
                    ),
                ),
                (
                    "status_changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="assets.system",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags (CTDB)",
                "ordering": ["tag_number"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("tag_number", models.CharField(blank=True, max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("skip", "Skip"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("skipped", "Skipped (duplicate)"),
                            ("failed", "Failed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="assets.importbatch",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_items",
                        to="assets.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Batch Item",
                "ordering": ["batch", "row_number"],
            },
        ),
        migrations.AddField(
            model_name="changerequest",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="change_requests",
                to="assets.tag",
            ),
        ),
        migrations.CreateModel(
            name="TagClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(blank=True, max_length=5)),
                ("description", models.TextField(blank=True)),
                (
                    "typical_tag_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Regex pattern for tag numbers of this class",
                        max_length=50,
                    ),
                ),
                ("requires_safety_review", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "discipline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tag_classes",
                        to="assets.discipline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag Class",
                "verbose_name_plural": "Tag Classes",
                "ordering": ["discipline", "name"],
            },
        ),
        migrations.AddField(
            model_name="tag",
            name="tag_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to="assets.tagclass",
            ),
        ),
        migrations.CreateModel(
            name="TagGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, db_index=True, max_length=50)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("loop", "Process Loop"),
                            ("shutdown_key", "Shutdown Key"),
                            ("cause_effect", "Cause & Effect"),
                            ("p_and_id", "P&ID"),
                            ("maintenance_plan", "Maintenance Plan"),
                            ("inspection_group", "Inspection Group"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tag_groups",
                        to="assets.plant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag Group",
                "ordering": ["group_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="TagGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Initiator, Final Element",
                        max_length=100,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.taggroup",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag Group Membership",
                "ordering": ["group", "sequence"],
                "unique_together": {("tag", "group")},
            },
        ),
        migrations.AddField(
            model_name="taggroup",
            name="tags",
            field=models.ManyToManyField(
                related_name="groups",
                through="assets.TagGroupMembership",
                to="assets.tag",
            ),
        ),
        migrations.CreateModel(
            name="TagStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("change_request_ref", models.CharField(blank=True, max_length=50)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="assets.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag Status History",
                "verbose_name_plural": "Tag Status Histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("process_type", models.CharField(blank=True, max_length=100)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="assets.area",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Unit",
                "ordering": ["area", "number"],
                "unique_together": {("area", "number")},
            },
        ),
        migrations.AddField(
            model_name="tag",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to="assets.unit",
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="systems",
                to="assets.unit",
            ),
        ),
        migrations.CreateModel(
            name="TagAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attribute_name", models.CharField(max_length=100)),
                ("attribute_value", models.TextField()),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("boolean", "Boolean"),
                            ("url", "URL"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("unit_of_measure", models.CharField(blank=True, max_length=30)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="assets.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag Attribute",
                "ordering": ["attribute_name"],
                "unique_together": {("tag", "attribute_name")},
            },
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["tag_number"], name="assets_tag_tag_num_f33c80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["status"], name="assets_tag_status_10141d_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["discipline"], name="assets_tag_discipl_239409_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["plant", "unit"], name="assets_tag_plant_i_8501a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["is_safety_critical"], name="assets_tag_is_safe_2f0354_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["is_deleted"], name="assets_tag_is_dele_5ce08b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="system",
            unique_together={("unit", "code")},
        ),
    ]
