# Generated by Django 5.2.11 on 2026-02-23 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "requires_tag_verification",
                    models.BooleanField(
                        default=True,
                        help_text="Does this document type require tag verification?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Document Type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("contractor", models.CharField(blank=True, max_length=200)),
                ("project_number", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="assets.discipline",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="assets.plant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "ordering": ["document_number"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "revision_number",
                    models.CharField(help_text="e.g. 0, A, B, 1, 2, P1", max_length=10),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ifr", "Issued for Review (IFR)"),
                            ("ifc", "Issued for Construction (IFC)"),
                            ("afc", "Approved for Construction (AFC)"),
                            ("approved", "Approved"),
                            ("superseded", "Superseded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("pass", "Pass"),
                            ("issues", "Has Issues"),
                            ("approved", "Approved with Override"),
                            ("skipped", "Verification Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("tags_found", models.PositiveIntegerField(default=0)),
                ("tags_valid_active", models.PositiveIntegerField(default=0)),
                ("tags_valid_void", models.PositiveIntegerField(default=0)),
                ("tags_not_found", models.PositiveIntegerField(default=0)),
                ("tags_shorthand", models.PositiveIntegerField(default=0)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("override_justification", models.TextField(blank=True)),
                ("revision_date", models.DateField(blank=True, null=True)),
                ("revision_purpose", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("checker", models.CharField(blank=True, max_length=200)),
                ("approver_name", models.CharField(blank=True, max_length=200)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="documents.document",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Revision",
                "ordering": ["document", "-created_at"],
                "unique_together": {("document", "revision_number")},
            },
        ),
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("checksum_md5", models.CharField(blank=True, max_length=32)),
                (
                    "extraction_method",
                    models.CharField(
                        blank=True,
                        help_text="pymupdf / pdfplumber / pypdf / ocr / image_ocr",
                        max_length=30,
                    ),
                ),
                ("page_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file",
                        to="documents.documentrevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document File",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="current_revision",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_document",
                to="documents.documentrevision",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.documenttype",
            ),
        ),
        migrations.CreateModel(
            name="TagDocumentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("valid_active", "Valid (Active)"),
                            ("valid_void", "Valid (Void — flag)"),
                            ("not_found", "Not Found in CTDB"),
                            ("shorthand_detected", "Shorthand Detected"),
                        ],
                        max_length=30,
                    ),
                ),
                ("raw_text", models.CharField(blank=True, max_length=200)),
                (
                    "page_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_shorthand", models.BooleanField(default=False)),
                ("original_shorthand", models.CharField(blank=True, max_length=200)),
                (
                    "document_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_links",
                        to="documents.documentrevision",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_links",
                        to="assets.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag-Document Link",
                "ordering": ["tag__tag_number"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_number"], name="documents_d_documen_dbcf06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_active"], name="documents_d_is_acti_e5a870_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tagdocumentlink",
            index=models.Index(
                fields=["tag", "verification_status"],
                name="documents_t_tag_id_36624d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tagdocumentlink",
            index=models.Index(
                fields=["document_revision"], name="documents_t_documen_b4d4a6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tagdocumentlink",
            unique_together={("tag", "document_revision")},
        ),
    ]
